// 1.MFE-with-react/child-vueapp/src/App.vue
<template>
  <div class="vue-inventory">
    <h2>Pharmacy Inventory (Vue Micro-Frontend)</h2>
    <InventoryList />
  </div>
</template>

<script>
import InventoryList from "./components/InventoryList.vue";

export default {
  components: {
    InventoryList,
  },
};
</script>

<style>
.vue-inventory {
  font-family: "Arial", sans-serif;
  padding: 20px;
  border: 4px solid #41b883;
  border-radius: 8px;
  background-color: #f0fdf4;
}
h2 {
  color: #35495e;
}
</style>

// 1.MFE-with-react/child-angular-product-catalog/src/app/app.component.ts
import { Component } from '@angular/core';
import { OrderComponent } from './order/order.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [OrderComponent],
  template: `
    <div class="angular-app-container">
      <h2>Order Management (Angular MFE)</h2>
      <app-order></app-order>
    </div>
  `,
  styles: [`
    .angular-app-container {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      padding: 20px;
      border: 4px solid #dd0031;
      background-color: #fff5f7;
      border-radius: 8px;
    }
    h2 {
      color: #a6120d;
    }
  `]
})
export class AppComponent { }
